### ISSUE TITLE
cannot install via pip

### ISSUE THREAD

**Issue by mpaglia0** [pelican-plugins/tipue-search#4]
Tried to install via pip but I got the message:
ERROR: Could not find a version that satisfies the requirement pelican-tipue-search
ERROR: No matching distribution found for pelican-tipue-search

**Comment by justinmayer** [comment]
Hi Maurizio. This is a known issue: the instructions describe a package that hasn't been published to PyPI yet, a situation which I will address very shortly. In the interim, please install via: `pip install https://github.com/pelican-plugins/tipue-search/archive/main.zip`

**Comment by radoeka** [comment]
Can this be fixed?  I ran into the same issue.

**Comment by mpaglia0** [comment]
> 
> 
> Can this be fixed? I ran into the same issue.

It is quite easy to let tipue-seach works also manually.
if you need a starting point I did it on my theme [Z](https://github.com/mpaglia0/Z)

**Comment by radoeka** [comment]
I have it working, that's not the issue.  Would like to have this working using 'pip install tipue-seach'.
That enables it to easily upgrade the package, when a new version becomes available.

**Comment by justinmayer** [comment]
I'm very sorry for the trouble mentioned in this issue, which I have just now resolved. Thank you for your patience. Following are the details…

1. I have created a new [Pelican Search](https://github.com/pelican-plugins/search) plugin. I highly suggest using that instead of Tipue Search.
2. This plugin and the repository are deprecated. The code is archived in the [Legacy Plugins Repository](https://github.com/getpelican/pelican-plugins/tree/master/tipue_search). This repository will eventually be deleted.
3. If you still want to use Tipue Search, even though it is abandoned and unmaintained, the installation instructions have been fixed in the README.
